#!/bin/bash

echo "🔐 BrainBased EMDR Platform - Foundation Setup"
echo "=============================================="
echo ""

echo "📋 This script will help you configure the essential foundations:"
echo "   - Authentication (Email templates, settings)"
echo "   - Storage (Buckets, policies)"
echo ""

echo "🎯 STEP 3: AUTHENTICATION CONFIGURATION"
echo "======================================"
echo ""
echo "1. Go to your Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/sqisjjtapmujcjmxlzjz"
echo ""
echo "2. Navigate to Authentication → Email Templates"
echo ""
echo "3. Configure these templates:"
echo ""
echo "   📧 WELCOME EMAIL:"
echo "   - Template: Welcome"
echo "   - Subject: Welcome to BrainBased EMDR Platform"
echo "   - Content: Professional welcome with role info"
echo ""
echo "   🔒 PASSWORD RESET:"
echo "   - Template: Reset Password"
echo "   - Subject: Reset Your BrainBased EMDR Platform Password"
echo "   - Content: Secure reset instructions"
echo ""
echo "   ✅ EMAIL VERIFICATION:"
echo "   - Template: Confirm Signup"
echo "   - Subject: Verify Your BrainBased EMDR Platform Account"
echo "   - Content: Verification instructions"
echo ""
echo "4. Go to Authentication → Settings"
echo "   - Site URL: http://localhost:5000"
echo "   - Add redirect URLs:"
echo "     * http://localhost:5000/auth/callback"
echo "     * http://localhost:5000/dashboard"
echo "     * http://localhost:5000/login"
echo ""
echo "5. Configure Password Policy:"
echo "   - Minimum Length: 8 characters"
echo "   - Require Uppercase: Yes"
echo "   - Require Lowercase: Yes"
echo "   - Require Numbers: Yes"
echo "   - Require Special Characters: Yes"
echo ""

echo "📁 STEP 4: STORAGE BUCKETS CONFIGURATION"
echo "======================================="
echo ""
echo "1. Go to Storage → Buckets"
echo ""
echo "2. Create these buckets:"
echo ""
echo "   📄 DOCUMENTS BUCKET:"
echo "   - Name: documents"
echo "   - Public: No"
echo "   - File Size Limit: 10MB"
echo "   - Allowed Types: PDF, DOC, DOCX, JPG, PNG"
echo ""
echo "   🎥 RECORDINGS BUCKET:"
echo "   - Name: recordings"
echo "   - Public: No"
echo "   - File Size Limit: 100MB"
echo "   - Allowed Types: MP4, WEBM, MOV"
echo ""
echo "   🏆 CERTIFICATES BUCKET:"
echo "   - Name: certificates"
echo "   - Public: No"
echo "   - File Size Limit: 5MB"
echo "   - Allowed Types: PDF, PNG, JPG"
echo ""
echo "3. Go to SQL Editor"
echo "4. Copy and paste the content from: supabase/storage-policies.sql"
echo "5. Run the script to create storage policies"
echo ""

echo "🧪 TESTING CHECKLIST"
echo "==================="
echo ""
echo "After configuration, test these:"
echo ""
echo "✅ AUTHENTICATION TESTS:"
echo "  - [ ] User registration works"
echo "  - [ ] Email verification works"
echo "  - [ ] Password reset works"
echo "  - [ ] Login/logout works"
echo "  - [ ] Role-based access works"
echo ""
echo "✅ STORAGE TESTS:"
echo "  - [ ] File upload works"
echo "  - [ ] File download works"
echo "  - [ ] Access control works"
echo "  - [ ] File organization works"
echo ""

echo "🚀 READY TO PROCEED?"
echo "==================="
echo ""
echo "Once you've completed the configuration:"
echo "1. Run: npm run dev"
echo "2. Test the system"
echo "3. Check the detailed checklist in: FOUNDATION_SETUP_CHECKLIST.md"
echo ""
echo "Need help? Check the troubleshooting section in the checklist."
echo ""
echo "🎯 Foundation setup will enable:"
echo "  - Professional user authentication"
echo "  - Secure document management"
echo "  - Session recording storage"
echo "  - Certificate generation and storage"
echo "  - Role-based access control"
echo "  - Compliance-ready audit trails"
echo ""
echo "✅ Your EMDR platform will be production-ready!" 