import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [
    react(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "client", "src"),
      "@shared": path.resolve(import.meta.dirname, "shared"),
      "@assets": path.resolve(import.meta.dirname, "attached_assets"),
    },
  },
  root: path.resolve(import.meta.dirname, "client"),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
  },
  optimizeDeps: {
    exclude: [
      '@radix-ui/react-separator',
      '@radix-ui/react-scroll-area',
      '@radix-ui/react-tabs',
      '@radix-ui/react-avatar',
      '@radix-ui/react-badge',
      '@radix-ui/react-progress',
      '@radix-ui/react-skeleton',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-toast',
      '@radix-ui/react-tooltip',
      '@radix-ui/react-dialog',
      '@radix-ui/react-popover',
      '@radix-ui/react-select',
      '@radix-ui/react-switch',
      '@radix-ui/react-checkbox',
      '@radix-ui/react-radio-group',
      '@radix-ui/react-slider',
      '@radix-ui/react-textarea',
      '@radix-ui/react-label',
      '@radix-ui/react-input',
      '@radix-ui/react-form',
      '@radix-ui/react-alert-dialog',
      '@radix-ui/react-aspect-ratio',
      '@radix-ui/react-breadcrumb',
      '@radix-ui/react-calendar',
      '@radix-ui/react-carousel',
      '@radix-ui/react-chart',
      '@radix-ui/react-checkbox',
      '@radix-ui/react-collapsible',
      '@radix-ui/react-command',
      '@radix-ui/react-context-menu',
      '@radix-ui/react-drawer',
      '@radix-ui/react-hover-card',
      '@radix-ui/react-input-otp',
      '@radix-ui/react-menubar',
      '@radix-ui/react-navigation-menu',
      '@radix-ui/react-pagination',
      '@radix-ui/react-resizable',
      '@radix-ui/react-sheet',
      '@radix-ui/react-sidebar',
      '@radix-ui/react-toggle',
      '@radix-ui/react-toggle-group',
    ],
    include: [
      'react',
      'react-dom',
      'lucide-react',
      '@tanstack/react-query',
      'wouter',
      'date-fns',
      'clsx',
      'tailwind-merge',
      'class-variance-authority',
      'tailwindcss-animate',
    ]
  },
  server: {
    fs: {
      strict: true,
      deny: ["**/.*"],
    },
  },
});
